 name: MegaLinter
 on: [push]
 jobs:
   mega-linter:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: MegaLinter
         uses: oxsecurity/megalinter@v8
         env:
           GITHUB_TOKEN: ${{ secrets.SCAN_TOKEN }}
